services:
  server:
    build: .
    container_name: bia
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      #DB_PWD: postgres
      DB_HOST: bia-pipeline.cx4q6caas2ti.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_SECRET_NAME: rds!db-31ced089-8889-4544-abde-00ce0d2cc64f
      DB_REGION: us-east-1